/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    // constants/ added after a real bug: REEL_STYLE_META's gradient classes
    // lived here as data and were silently never generated by Tailwind
    // (JIT only scans files matched by this glob) — worked by accident in
    // dark mode, invisible white-on-white in light mode. Any future
    // Tailwind-class-as-data pattern in constants/ needs this to work at all.
    './constants/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg:           'rgb(var(--bg)           / <alpha-value>)',
        card:         'rgb(var(--card)         / <alpha-value>)',
        nav:          'rgb(var(--nav)          / <alpha-value>)',
        border:       'rgb(var(--border)       / <alpha-value>)',
        accent:       'rgb(var(--accent)       / <alpha-value>)',
        success:      'rgb(var(--success)      / <alpha-value>)',
        danger:       'rgb(var(--danger)       / <alpha-value>)',
        'text-primary':'rgb(var(--text)        / <alpha-value>)',
        muted:        'rgb(var(--muted)        / <alpha-value>)',
      },
      fontFamily: {
        sans: ['var(--font-body)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'var(--font-body)', 'system-ui', 'sans-serif'],
      },
      // Gamified reel-style cards (AI Reel Generator) — CSS-only "trading
      // card" treatment (idle float, holographic shimmer sweep, pop-in
      // checkmark, pulsing selection glow) since no real image/video assets
      // can be sourced for this. Named here (not inline/arbitrary values)
      // so they're real static classes Tailwind's scanner picks up cleanly.
      keyframes: {
        'reel-float':  { '0%,100%': { transform: 'translateY(0) rotate(var(--tilt, 0deg))' }, '50%': { transform: 'translateY(-5px) rotate(var(--tilt, 0deg))' } },
        'reel-shimmer': { '0%': { transform: 'translateX(-120%) translateY(-120%) rotate(25deg)' }, '100%': { transform: 'translateX(120%) translateY(120%) rotate(25deg)' } },
        'reel-pop-in': { '0%': { transform: 'scale(0)', opacity: '0' }, '60%': { transform: 'scale(1.25)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'reel-glow':   { '0%,100%': { boxShadow: '0 0 0 0 rgba(255,255,255,0.0), 0 8px 20px -4px rgba(0,0,0,0.35)' }, '50%': { boxShadow: '0 0 24px 4px rgba(255,255,255,0.45), 0 8px 24px -4px rgba(0,0,0,0.4)' } },
      },
      animation: {
        'reel-float':   'reel-float 4.5s ease-in-out infinite',
        'reel-shimmer': 'reel-shimmer 3s ease-in-out infinite',
        'reel-pop-in':  'reel-pop-in 0.45s cubic-bezier(0.34,1.56,0.64,1)',
        'reel-glow':    'reel-glow 1.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
